# Configuration for https://goreleaser.com/
project_name: yq

before:
  hooks:
    - go mod download
builds:
  - binary: yq
    main: ./
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
release:
  disable: true

snapshot:
  name_template: "git-{{.ShortCommit}}"

archive:
  format: binary

artifactories:
  - name: production
    mode: binary
    target: '{{ .Env.ARTIFACTORY_REPO }}/{{ .Os }}/{{ .ProjectName }}/{{ .Version }}'
    username: '{{ .Env.ARTIFACTORY_USER }}'
